
const produits=[
    {
        id:1 ,
        nom:"crayon graphite",
        marque:"Faber-Castell",
        prix:450,
        categorie:"Crayons",
        image:"crfbtg.png",
        populaire:true,
    },
    {
        id:2,
        nom:"crayon graphite",
        marque:"Faber-Castell",
        prix:350,
        categorie:"Crayons",
        image:"../images/fabercastle.png",
        populaire:false,

    },
    {
        id:3,
        nom:"crayon graphite",
        marque:"Faber-Castell",
        prix:350,
        categorie:"Crayons",
        image :"../images/crfb.png",
        populaire:false,
    },
    {
       id:4,
        nom:"crayon graphite",
        marque:"HHHOUU",
        prix:560,
        categorie:"Crayons",
        image :"../images/crayonHHHOUU.png",
        populaire:true,
    },
    {
        id:5,
        nom:"crayon graphite",
        marque:"Faber-Castell",
        prix:350,
        categorie:"Crayons",
        image:"../images/crayontechno.png",
        populaire:false,
    },
    {
        id:6,
        nom:"crayon de couleur ",
        marque:"TECHNO",
        prix:350,
        categorie:"Crayons",
        image:"../images/couleurtechno.png",
        populaire:false,
    },
    {
        id:7,
        nom:"crayon de couleur",
        marque:"MAPED",
        prix:600,
        categorie:"Crayons",
        image:"../images/couleurmaped.png",
        populaire:false,
    },
    {
        id:8,
        nom:"crayon de couleur",
        marque:"MAPED",
        prix:600,
        categorie:"Crayons",
        image:"../images/clrca.png",
        populaire:false,
    },
    {
         id:9,
        nom:"crayon de couleur",
        marque:"Faber-Castell",
        prix:600,
        categorie:"Crayons",
        image:"../images/clrfb.png",
       populaire:false,

    },
    {
         id:10,
        nom:"crayon de couleur",
        marque:"Faber-Castell",
        prix:2000,
        categorie:"Crayons",
        image:"../images/clrfb2.png",
        populaire:true,
    },
    {
         id:11,
        nom:"crayon de couleur",
        marque:"Faber-Castell",
        prix:600,
        categorie:"Crayons",
        image:"../images/clrfb3.png",
        populaire:false,
    },
    {
      id:12,
        nom:"peinture à l'huile",
        marque:"",
        prix:490,
        categorie:"peinture",
        image:"../images/oil1.png",
        populaire:false,
    },

    {
        id:13,
        nom:"peinture à l'huile",
        marque:"",
        prix:570,
        categorie:"peinture",
        image:"../images/oil2.png",
        populaire:false,
    },
    {
        id:14,
        nom:"peinture à l'huile",
        marque:"",
        prix:700,
        categorie:"peinture",
        image:"../images/oil3.png",
        populaire:false,

    },
    {
        id:15,
        nom:"peinture acrylique",
        marque:"",
        prix:570,
        categorie:"peinture",
        image:"../images/acr2.png",
        populaire:false,

    },
    {
        id:16,
        nom:"pinceaux",
        marque:"",
        prix:300,
        categorie:"Pinceaux",
        image:"../images/pinc2.png",
        populaire:false,

    },
    {
         id:17,
        nom:"peinture acrylique",
        marque:"",
        prix:1000,
        categorie:"peinture",
        image:"../images/acr3.png",
        populaire:false,

    },
    {
         id:18,
        nom:"peinture acrylique",
        marque:"",
        prix:880,
        categorie:"peinture",
        image:"../images/acr4.png",
        populaire:false,

    },
    {
         id:19,
        nom:"peinture acrylique",
        marque:"",
        prix:1000,
        categorie:"peinture",
        image:"../images/acr1.png",
       populaire:false,

    },
    {
         id:20,
        nom:"peinture à l'eau",
        prix:1000,
        categorie:"peinture",
        image:"../images/wtr1.png",
        populaire:false,

    },
    {
         id:21,
        nom:"pinceaux",
        prix:250,
        categorie:"Pinceaux",
        image:"../images/pinc1.png",
       populaire:false,

    },
];